### ISSUE TITLE
Fonts get stripped out

### ISSUE THREAD

**Issue by RyanRoberts** [Mcgurk-Adam/OptimizeFont#1]
Hey, first up I just want to say thanks for making this site! It's such a handy tool for lazy people like me ;)

Anyway I'm encountering a problem where I paste this in:

``` <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,400;1,500&display=swap" rel="stylesheet"> 
```

And I get this:

```
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preload" as="style" href="https://fonts.gstatic.com/&display=swap">
<link rel="stylesheet" href="https://fonts.gstatic.com/&display=swap" media="print" onload="this.media='all'">
<noscript>
	<link rel="stylesheet" href="https://fonts.gstatic.com/&display=swap">
</noscript>
```

I've tried different browsers, disabling adblockers, etc.

🤔

**Comment by Mcgurk-Adam** [comment]
@RyanRoberts - thanks so much for reaching out!! Love hearing when people enjoy using what I've built!

I'm not able to replicate in Chrome, Safari, or Firefox on Mac. What OS are you using? That might have something to do with it....in any case, super weird and I'd love to get to the bottom of it :)

**Comment by Mcgurk-Adam** [comment]
Also, I'm curious....not saying this is the solution, I'm just more curious about the answer...

What happens if you paste in just the url? ie - 
````bash
https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,400;1,500&display=swap
````
I'm curious if you get a different response. 

Super weird bug you've run across!!! Thanks for bringing it up!

**Comment by RyanRoberts** [comment]
@Mcgurk-Adam Hey there, thanks for the quick responses. 

I don't know if this is new from Google or not but the markup it gives you includes a preconnect tag and I was pasting that in along with the font tag:

```
<link rel="preconnect" href="https://fonts.gstatic.com"> 
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet">
```

I hadn't even noticed at the time! Just pasting the font link tag works.
